// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tadas_SOA_Repeat_CA.Data;

#nullable disable

namespace Tadas_SOA_Repeat_CA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230811082110_removedGameCategoriesField")]
    partial class removedGameCategoriesField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tadas_SOA_Repeat_CA.Models.AllCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            category = "Platform"
                        },
                        new
                        {
                            Id = 2,
                            category = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            category = "Action"
                        },
                        new
                        {
                            Id = 4,
                            category = "Sandbox"
                        },
                        new
                        {
                            Id = 5,
                            category = "Survival"
                        });
                });

            modelBuilder.Entity("Tadas_SOA_Repeat_CA.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nintendo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mojang Studios"
                        });
                });

            modelBuilder.Entity("Tadas_SOA_Repeat_CA.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Owned")
                        .HasColumnType("bit");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeveloperId = 1,
                            Name = "Super Mario Bros.",
                            Owned = true,
                            Publisher = "Nintendo",
                            RecordCreationDate = new DateTime(2023, 8, 11, 9, 21, 10, 681, DateTimeKind.Local).AddTicks(711),
                            ReleaseDate = new DateTime(1985, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DeveloperId = 1,
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Owned = true,
                            Publisher = "Nintendo",
                            RecordCreationDate = new DateTime(2023, 8, 11, 9, 21, 10, 681, DateTimeKind.Local).AddTicks(759),
                            ReleaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DeveloperId = 2,
                            Name = "Minecraft",
                            Owned = false,
                            Publisher = "Mojang",
                            RecordCreationDate = new DateTime(2023, 8, 11, 9, 21, 10, 681, DateTimeKind.Local).AddTicks(761),
                            ReleaseDate = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Tadas_SOA_Repeat_CA.Models.GameCategory", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("GameCategories");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            GameId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            GameId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            GameId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            GameId = 3,
                            CategoryId = 4
                        },
                        new
                        {
                            GameId = 3,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("Tadas_SOA_Repeat_CA.Models.AllCategories", b =>
                {
                    b.HasOne("Tadas_SOA_Repeat_CA.Models.Game", null)
                        .WithMany("Categories")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Tadas_SOA_Repeat_CA.Models.Game", b =>
                {
                    b.HasOne("Tadas_SOA_Repeat_CA.Models.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("Tadas_SOA_Repeat_CA.Models.GameCategory", b =>
                {
                    b.HasOne("Tadas_SOA_Repeat_CA.Models.AllCategories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tadas_SOA_Repeat_CA.Models.Game", "Game")
                        .WithMany("GameCategories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Tadas_SOA_Repeat_CA.Models.Game", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("GameCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
